backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
local_backend:
  # when using a custom proxy server port
  url: http://localhost:8082/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']

media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://gebouwen-door-vrouwen.netlify.app
display_url: https://www.gebouwendoorvrouwen.com 
logo_url: "/static/img/gdv-eyes.png"

# Please run "npx netlify-cms-proxy-server" for local backend
publish_mode: editorial_workflow

collections:
  - label: "Locations"
    label_singular: "Location"
    name: "location"
    extension: "md"
    folder: "src/content/location"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: "location" } 
      - { label: "Project", name: "title", widget: "string" } 
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "body", widget: "markdown" } 
      - { label: "Agency", name: "agency", widget: "string" }
      - { label: "Architect", name: "architect", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "image"
        default: "./static/img/default.png"
        choose_url: true
        media_library:
          config:
            multiple: true
      - widget: relation
        label: "Tags"
        name: "location_tags"
        collection: "location_tag"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
        multiple: true
      - widget: string
        label: "Address"
        name: "address"
        required: false
      - widget: map
        label: "Geolocation"
        name: "location"
        create: true
        required: false
  - label: "Tags"
    label_singular: "Tag"
    name: "location_tag"
    extension: "md"
    folder: "src/content/location_tag"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title Dutch", name: "title", widget: "string" }
      - { label: "Title English", name: "title_en", widget: "string", required: false }
      - { label: "Marker", name: "marker", widget: "string" }
      - label: "Marker Image"
        name: "marker_img"
        widget: "image"
        default: "./static/img/m1.png"
        choose_url: true
        required: false
        media_library:
          config:
            multiple: false
      - { label: "Tags", name: "tags", widget: "hidden", default: "location_tag" }
  - label: "Pages"
    name: "page"
    extension: "md"
    folder: "src/content/pages"
    create: true
    editor:
      preview: true
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.json"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - widget: relation
                label: "link"
                name: "link"
                collection: "page"
                search_fields: ["title"]
                value_field: "{{slug}}"
                display_fields: ["title"]
                multiple: false
      - label: "Settings"
        name: "settings"
        file: "src/_data/settings.json"
        fields:
          - { label: Author, name: AUTHOR, widget: string }
          - { label: Title, name: TITLE, widget: string }
          - { label: Description, name: DESCRIPTION, widget: text }
          - { label: Loader, name: ENABLE_LOADER, widget: boolean }
          - { label: Map Center, name: MAPBOX_CENTER, widget: map }
          - label: Map Zoom
            name: MAPBOX_DEFAULT_ZOOM
            widget: select
            default: { label: "country", value: 9 }
            options:
              - { label: "country", value: 9 }
              - { label: "city", value: 11 }
              - { label: "district", value: 13 }
          - { label: Background color, name: COLOR_BG, widget: color, default: "#f7f7f7" }
          - { label: Text color, name: COLOR_FRONT, widget: color,  default: "#333" }
          - { label: Highlight color, name: COLOR_HIGHLIGHT, widget: color, default: "#ff6f61" }
          - { label: Font, name: FONT_FAMILY, widget: string, default: "-apple-system, BlinkMacSystemFont, avenir next, avenir, segoe ui, helvetica neue, helvetica, Cantarell, Ubuntu, roboto, noto, arial, sans-serif;"}
          - label: "Logo Image"
            name: "LOGO"
            widget: "image"
            choose_url: true
            required: false
            media_library:
              config:
                multiple: false
          - label: "Icon"
            name: "ICON"
            widget: "image"
            choose_url: true
            required: false
            media_folder: "./src/static/icons"
            media_library:
              config:
                multiple: false
          - label: "Default placeholder"
            name: "PLACEHOLDER_IMAGE"
            widget: "image"
            choose_url: true
            required: false
            media_library:
              config:
                multiple: false

